"""Add card features priority assigned_to labels

Revision ID: 72430dbe7aea
Revises: 98481097aff6
Create Date: 2026-05-17 14:40:49.960755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72430dbe7aea'
down_revision: Union[str, Sequence[str], None] = '98481097aff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('priority', sa.String(length=50), nullable=True))
    op.add_column('cards', sa.Column('labels', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'labels')
    op.drop_column('cards', 'priority')
    # ### end Alembic commands ###
