"""Add description and color to Board

Revision ID: f0012f7db523
Revises: 3b6dd50c4e8e
Create Date: 2026-04-17 06:20:53.193144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0012f7db523'
down_revision: Union[str, Sequence[str], None] = '3b6dd50c4e8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column('boards', sa.Column('color', sa.String(length=50), server_default='#0079bf', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'color')
    op.drop_column('boards', 'description')
    # ### end Alembic commands ###
